package main

// commandDescriptions is the compiled help catalog for root, group, and leaf
// commands. Keys use canonical route paths, plus explicit CLI aliases.
var commandDescriptions = map[string]string{
	"health":                  "Check daemon health.",
	"doctor":                  "Run environment diagnostics.",
	"protocol":                "Print the agent protocol contract.",
	"version":                 "Print the dibs version and build revision.",
	"init":                    "Register the current Git repository and worktree, then install agent instructions.",
	"watch":                   "Show ready work, active leases, blockers, and recent events in a read-only live board.",
	"hooks":                   "Integrate Claude Code or Codex with the issue lifecycle.",
	"hooks install":           "Install a read-only SessionStart ready view in project hook config.",
	"hooks session-start":     "Provide ready work as agent context without claiming it.",
	"hooks complete":          "Mark one issue run as complete after its acceptance criteria pass.",
	"daemon":                  "Start or stop the local daemon.",
	"daemon start":            "Start dibsd and wait for a healthy socket.",
	"daemon stop":             "Stop the local dibsd process for the configured database.",
	"stats":                   "Show read-only project execution statistics.",
	"project":                 "Manage projects.",
	"repo":                    "Manage repositories.",
	"worktree":                "Manage worktrees.",
	"artifact-root":           "Manage repository artifact roots.",
	"artifact":                "Manage registered artifacts.",
	"export":                  "Export coordinator state.",
	"issue":                   "Manage issues.",
	"dependency":              "Alias for issue dependency commands.",
	"ls":                      "List issues (alias for issue list).",
	"show":                    "Show an issue (alias for issue get).",
	"project add":             "Create a project with a key and display name.",
	"project list":            "List registered projects.",
	"repo add":                "Register a repository in a project.",
	"repo list":               "List registered repositories.",
	"repo relocate":           "Move a repository and its registered worktree paths after verifying Git identity.",
	"worktree register":       "Register or update a worktree.",
	"worktree list":           "List registered worktrees.",
	"worktree prune":          "Remove stale records for missing worktree paths.",
	"worktree unregister":     "Remove one safe-to-delete worktree record.",
	"artifact-root add":       "Register a root directory for repository artifacts.",
	"artifact-root list":      "List registered artifact roots.",
	"artifact register":       "Register an artifact file in a repository.",
	"artifact list":           "List registered artifacts.",
	"export jsonl":            "Stream coordinator state as normalized JSONL.",
	"issue cancel":            "Cancel an issue (requires DIBS_OPERATOR_TOKEN).",
	"issue claim":             "Acquire a lease to work on an issue.",
	"issue close":             "Close a leased issue as done or cancelled.",
	"issue create":            "Create an issue.",
	"issue create-form":       "Create an issue with an interactive form.",
	"issue dependency":        "Manage dependencies between issues.",
	"issue edit":              "Edit issue fields (alias of update).",
	"issue events":            "Read the activity timeline for an issue.",
	"issue get":               "Show one issue by ID or short ID.",
	"issue handoff":           "Record a HANDOFF note and release the lease.",
	"issue heartbeat":         "Extend the active issue lease.",
	"issue link":              "Link an artifact to an issue.",
	"issue list":              "List issues with optional filters.",
	"issue note":              "Add or read issue notes.",
	"issue operator-close":    "Force-close an issue (requires DIBS_OPERATOR_TOKEN).",
	"issue operator-release":  "Clear a stuck lease and return the issue to open (requires DIBS_OPERATOR_TOKEN).",
	"issue operator-reopen":   "Reopen a terminal issue (requires DIBS_OPERATOR_TOKEN).",
	"issue ready":             "List actionable issues that are not leased.",
	"issue release":           "Release a lease without closing the issue.",
	"issue run":               "Claim, run a child command, then close or hand off the issue; --require-complete needs explicit agent completion.",
	"issue tag":               "Add, remove, or list issue tags.",
	"issue unlink":            "Remove an issue-to-artifact link.",
	"issue update":            "Update issue fields such as title, priority, or status.",
	"issue dependency add":    "Add a dependency or relation to another issue.",
	"issue dependency remove": "Remove a dependency or relation between issues.",
	"issue note add":          "Add a note to an issue.",
	"issue note list":         "List notes on an issue.",
	"issue tag add":           "Add a namespaced tag to an issue.",
	"issue tag remove":        "Remove a tag from an issue.",
	"issue tag list":          "List tags on an issue.",
	"issue events list":       "List activity events for an issue.",
}
